package com.example.protocol.v1

object ProtocolConstants {
    const val SCHEMA_VERSION = "1"

    // Channels
    const val CHANNEL_SENSORS = "sensors"
    const val CHANNEL_CAMERA = "camera"
    const val CHANNEL_CONTROL = "control"

    // Message Types
    const val TYPE_CHANNEL_HELLO = "CHANNEL_HELLO"
    const val TYPE_INSTRUMENT_DESCRIPTOR = "INSTRUMENT_DESCRIPTOR"
    const val TYPE_MEASUREMENT_PACKET = "MEASUREMENT_PACKET"
    const val TYPE_ERROR_ENVELOPE = "ERROR_ENVELOPE"

    // Camera Message Types
    const val TYPE_CAMERA_PREVIEW_FRAME = "CAMERA_PREVIEW_FRAME"
    const val TYPE_CAMERA_SCIENTIFIC_FRAME = "CAMERA_SCIENTIFIC_FRAME"
    const val TYPE_CAMERA_CONTROL_REQUEST = "CAMERA_CONTROL_REQUEST"
    const val TYPE_CAMERA_CONTROL_RESULT = "CAMERA_CONTROL_RESULT"
    const val TYPE_CAMERA_CAPABILITIES = "CAMERA_CAPABILITIES"
    const val TYPE_CAMERA_STATE = "CAMERA_STATE"
    const val TYPE_SCIENTIFIC_CAPTURE_REQUEST = "SCIENTIFIC_CAPTURE_REQUEST"
    const val TYPE_SCIENTIFIC_CAPTURE_RESULT = "SCIENTIFIC_CAPTURE_RESULT"
    const val TYPE_SCIENTIFIC_FRAME_ACK = "SCIENTIFIC_FRAME_ACK"
    const val TYPE_CAMERA_INVENTORY = "CAMERA_INVENTORY"
}
